= Command-Line Tool for Signal Processing

:author: Christina Praml
:date: September 10, 2023

== Introduction

This is a command-line tool built with Python 3.8 that provides various signal processing functionalities including WAV file plotting, Fourier analysis, Gabor transformation, and spectrogram generation. The tool uses a virtual environment for dependency management, and you can install the required dependencies by using the provided `requirements.txt` file.

== Installation

Before you begin, make sure you have Python 3.8 (or later) installed on your system.

=== Create a Virtual Environment

It's recommended to create a virtual environment for this project to manage dependencies. You can create one using the following commands:

[source,shell]
python3.8 -m venv venv
source venv/bin/activate # On Windows, use 'venv\Scripts\activate'


=== Install Dependencies

Once the virtual environment is activated, you can install the required dependencies using pip:

[source,shell]
pip install -r requirements.txt


== Usage

The tool provides the following subcommands:

- WAV: Plots .wav files
- FOURIER: Performs Fourier analysis
- GABOR: Performs Gabor transformation, uses own implementation by default
- SPECGRAM: Uses matplotlib specgram function to generate a spectrogram

Each of the subcommands plots the output as a graph.

=== WAV Subcommand

Use this subcommand for plotting .wav files.

Usage:
[source,shell]
python main.py WAV [-h] input

- input: Path to the input file
- h: Shows a help message

Example usage:
[source,shell]
python main.py WAV input/Export1/Klavier_A_leicht.wav

=== FOURIER Subcommand

This subcommand performs Fourier analysis on the input data and plot the output as a graph.

Usage:
[source,shell]
python main.py FOURIER [-h] [--own] [--xlim XLIM] input

- input: Path to the input file
- h: Show the help message and exit
- own: Whether to use the own implementation or the library implementation
- xlim: The x limit for the plot

Example usage:
[source,shell]
python main.py FOURIER --own --xlim 2000 input/Export1/Klavier_A_leicht.wav

=== GABOR Subcommand

This subcommand applies the Gabor transformation to the input data and plots the output as a spectrogram.

Usage:
[source,shell]
python main.py GABOR [-h] [--own] [--num_data NUM_DATA] [--nfft NFFT] [--noverlap NOVERLAP] [--ylim YLIM] input

- input: Path to the input file
- h: Show the help message and exit
- own: Whether to use the own implementation or the library implementation
- num_data: The number of data values to be averaged
- nfft: The number of data points used in each block for the FFT
- noverlap: The number of points of overlap between blocks
- ylim: The y limit for the plot

Example usage:
[source,shell]
python main.py GABOR --own --ylim 1000 input/Export1/Klavier_A_leicht.wav

=== SPECGRAM Subcommand

This subcommand generates a spectrogram from the input data.

Usage:
[source,shell]
python main.py SPECGRAM [-h] [--nfft NFFT] [--noverlap NOVERLAP] [--xlim XLIM] [--ylim YLIM] input

- input: Path to the input file
- h: Show the help message and exit
- nfft: The number of data points used in each block for the FFT
- noverlap: The number of points of overlap between blocks
- xlim: The x limit for the plot
- ylim: The y limit for the plot

Example usage:
[source,shell]
python main.py SPECGRAM input/Export1/Klavier_A_leicht.wav
